#!/usr/bin/env php
<?php

define("__ROOT__", __DIR__);
require_once(__ROOT__ . '/config/config.php');
require_once("libs/functions/auto_load.php");
use Libs\Console;

$console = new Console();

exit();
